### ISSUE TITLE
why check for latlon for final table

### ISSUE THREAD

**Issue by Paul-Carvalho** [noaa-nwfsc/FishSET#114]
When saving the final table to fishset database, the user must select lat lon coordinates. Look back at why we check for this and see if this is necessary when using the port table for the starting location.

**Comment by paulcarvalho** [comment]
This really only needs to be checked if users are selecting lat-lon coordinates as the starting location. This has been changed to allow users to skip this input and still pass the data checks

**Comment by Paul-Carvalho** [comment]
The model checks were previously designed to automatically search for lat-lon variables by searching for "lat" and "lon" patterns in variables names. Consequently, this would get other variables with this pattern that are not coordinates (e.g., a variable with the word "extrapolated" because it contains "lat"). This was changed to make the user select variables manually, but now we realize this isn't always needed. Now users select lat-lon for data checks only if using coordinates for starting location. Otherwise the field is left blank and will still pass the data checks.
