### ISSUE TITLE
assignment_column duplicated description

### ISSUE THREAD

**Issue by mle2718** [noaa-nwfsc/FishSET#183]
``help(assignment_column)`` produces  a duplicated description.
I tried to fix it with 41dd998c92a11a1077778584fadedfe8cc5bc73f,  but I don't think I did it properly, because when I reinstall FishSET, the duplicate description stays.

**Comment by Paul-Carvalho** [comment]
@mle2718, I updated this in a new branch linked to this issue and it should be fixed. The documentation doesn't automatically update when the .R script is changed. We have to run devtools::document(), which rewrite the .md file used for package documentation. Let me know if this doesn't update for you after reinstalling from the master branch.

**Comment by mle2718** [comment]
oh nice.  Thanks @Paul-Carvalho
